/// Build script — auto-generates `SUPPORTED_LANGS` from the contents of
/// `lang/*.ftl`.  Drop a new `.ftl` file into `lang/` and the next build
/// will pick it up automatically; no manual code changes required.
///
/// Output: `$OUT_DIR/supported_langs.rs`
/// Usage in `src/i18n.rs`:
///   include!(concat!(env!("OUT_DIR"), "/supported_langs.rs"));
use std::{env, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let lang_dir = Path::new(&manifest_dir).join("i18n");

    // Re-run whenever any FTL file is added, removed, or changed.
    println!("cargo:rerun-if-changed=i18n/");

    let mut entries: Vec<(String, String)> = Vec::new();

    let read_dir =
        fs::read_dir(&lang_dir).unwrap_or_else(|e| panic!("cannot read i18n/ directory: {e}"));

    for entry in read_dir {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("ftl") {
            continue;
        }
        let code = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap()
            .to_string();
        let content = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));

        // Extract the `lang-name = <autonym>` line.
        let autonym = content
            .lines()
            .find_map(|line| {
                line.trim()
                    .strip_prefix("lang-name")
                    .and_then(|rest| rest.trim_start().strip_prefix('='))
                    .map(|v| v.trim().to_string())
            })
            // Fall back to the code itself when the key is absent.
            .unwrap_or_else(|| code.clone());

        entries.push((code, autonym));
    }

    // Sort alphabetically by language code for a deterministic output.
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::from(
        "/// Auto-generated by build.rs — do not edit by hand.\n\
         /// To add a language: drop a `i18n/<code>.ftl` file with a\n\
         /// `lang-name = <autonym>` key and rebuild.\n\
         pub const SUPPORTED_LANGS: &[(&str, &str)] = &[\n",
    );
    for (code, name) in &entries {
        let name_esc = name.replace('\\', "\\\\").replace('"', "\\\"");
        src.push_str(&format!("    (\"{code}\", \"{name_esc}\"),\n"));
    }
    src.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("supported_langs.rs");
    fs::write(&out_path, src).unwrap_or_else(|e| panic!("cannot write supported_langs.rs: {e}"));
}
