//! Minimal i18n support for zion.
//!
//! FTL files are fetched on demand from `/i18n/<code>.ftl`, which are served
//! as static assets by Trunk.  This keeps the WASM binary small regardless of
//! how many language files are provided.
//!
//! # Usage
//!
//! ```rust
//! // At startup (before mounting components):
//! i18n::init_from_browser().await;
//!
//! // After config loads, re-apply if user has a preference:
//! if let Some(lang) = cfg.get(".my.config.ui.language") {
//!     i18n::init(&lang).await;
//! }
//!
//! // Translate a key:
//! let label = t("btn-save");               // → "Save" / "Lagre"
//! let msg   = tf("msg-set", &[("path", ".my.aliases.bob"), ("value", "did:ma:...")]);
//! ```
//!
//! Unknown keys fall back to the key name itself.

use std::cell::RefCell;
use std::collections::HashMap;
use wasm_bindgen::JsCast;
use wasm_bindgen_futures::JsFuture;

thread_local! {
    static MESSAGES: RefCell<HashMap<String, String>> = RefCell::default();
    static CURRENT_LANG: RefCell<String> = RefCell::new("en".into());
}

/// Detect the browser's preferred language and initialise i18n.
///
/// Uses `window.navigator.language`. Falls back to English on any error.
pub async fn init_from_browser() {
    let lang = web_sys::window()
        .map(|w| w.navigator().language().unwrap_or_default())
        .unwrap_or_default();
    let _ = init(&lang).await;
}

/// (Re-)initialise i18n for the given BCP-47 language tag.
///
/// Fetches `/i18n/<code>.ftl` via the browser Fetch API.  Tries candidates
/// in order (`lang-Script`, `lang`, then `en`) until one succeeds.
///
/// Returns `true` if the requested language (or a normalised variant) was
/// found, `false` if the runtime fell back to English.
pub async fn init(lang: &str) -> bool {
    let candidates = normalize(lang);
    let (code, ftl) = load_ftl(&candidates).await;
    let map = parse(&ftl);
    // Never replace a working translation table with an empty one.
    // If the FTL fetch failed (network glitch, bad language code, Trunk
    // hot-reload gap, etc.) load_ftl returns an empty string and parse
    // produces an empty map.  Keep the current translations so that
    // subsequent t()/tf() calls still return readable strings.
    if map.is_empty() {
        return false;
    }
    let found = candidates.contains(&code);
    CURRENT_LANG.with(|l| *l.borrow_mut() = code);
    MESSAGES.with(|m| *m.borrow_mut() = map);
    found
}

/// Return the active language code (`"en"`, `"nb"`, …).
pub fn lang() -> String {
    CURRENT_LANG.with(|l| l.borrow().clone())
}

/// Look up a translation key.
///
/// Returns the localised string, or the key name itself when not found.
pub fn t(key: &str) -> String {
    MESSAGES.with(|m| {
        m.borrow()
            .get(key)
            .cloned()
            .unwrap_or_else(|| key.to_string())
    })
}

/// Look up a translation key and substitute variables.
///
/// `vars` is a slice of `("varname", "value")` pairs.
/// Replaces every `{ $varname }` occurrence in the translated string.
pub fn tf(key: &str, vars: &[(&str, &str)]) -> String {
    let mut s = t(key);
    for (var, val) in vars {
        s = s.replace(&format!("{{ ${var} }}"), val);
    }
    s
}

pub fn msg_jobs_cancelled() -> String {
    t("msg-jobs-cancelled")
}

// ── Internal helpers ───────────────────────────────────────────────────────

/// Try each candidate FTL file in order; fall back to English.
///
/// Returns `(code_loaded, ftl_text)`.
async fn load_ftl(candidates: &[String]) -> (String, String) {
    for code in candidates {
        if let Ok(s) = fetch_text(&format!("/i18n/{code}.ftl")).await {
            return (code.clone(), s);
        }
    }
    // Final fallback: English
    let s = fetch_text("/i18n/en.ftl").await.unwrap_or_default();
    ("en".to_string(), s)
}

/// Fetch a text resource from `url` via the browser Fetch API.
async fn fetch_text(url: &str) -> Result<String, String> {
    let window = web_sys::window().ok_or("no window")?;
    let resp_val = JsFuture::from(window.fetch_with_str(url))
        .await
        .map_err(|e| format!("{e:?}"))?;
    let resp: web_sys::Response = resp_val
        .dyn_into()
        .map_err(|_| "response cast failed".to_string())?;
    if !resp.ok() {
        return Err(format!("HTTP {}", resp.status()));
    }
    let text_promise = resp.text().map_err(|e| format!("{e:?}"))?;
    let text_val = JsFuture::from(text_promise)
        .await
        .map_err(|e| format!("{e:?}"))?;
    Ok(text_val.as_string().unwrap_or_default())
}

// `SUPPORTED_LANGS` is auto-generated by build.rs from the `i18n/*.ftl`
// files — drop a new FTL file and rebuild to have it appear automatically.
include!(concat!(env!("OUT_DIR"), "/supported_langs.rs"));

/// Normalise a BCP-47 tag to an ordered list of candidate `.ftl` file codes,
/// from most-specific to least-specific.
///
/// Both `-` and `_` are accepted as separators; the *semantic* separator is
/// capitalisation:
///
/// | Pattern | Role | Example |
/// |---------|------|---------|
/// | all-lowercase | language | `zh`, `nb`, `sr` |
/// | Title-case    | script   | `Hans`, `Hant`, `Cyrl`, `Latn` |
/// | ALL-CAPS      | region   | `TW`, `NO`, `GB` |
///
/// A 4-letter all-lowercase part is treated as a lowercased script subtag and
/// is normalised to Title case (`hans` → `Hans`).
/// `no` is mapped to `nb` (Norwegian Bokmål).
///
/// Candidates are ordered from most-specific to least-specific; the final
/// fallback to `en` happens in [`load_ftl`].
///
/// Examples:
/// - `"zh-Hans-TW"` / `"zh_Hans_TW"` → `["zh-Hans-TW", "zh-Hans", "zh"]`
/// - `"sr-Cyrl"` → `["sr-Cyrl", "sr"]`
/// - `"nb-NO"` → `["nb-NO", "nb"]`
/// - `"en-GB"` → `["en-GB", "en"]`
fn normalize(lang: &str) -> Vec<String> {
    // Handle private-use subtags such as `art-x-lyaric` (BCP-47 §2.2.7).
    // These contain `-x-` and must be passed through verbatim since the
    // part-by-part classifier below would mangle them.
    let normalised_input = lang.replace('_', "-").to_lowercase();
    if normalised_input.contains("-x-") {
        return vec![normalised_input];
    }

    let mut language = "en".to_string();
    let mut script: Option<String> = None;
    let mut region: Option<String> = None;

    for part in lang.split(['-', '_']).filter(|s| !s.is_empty()) {
        let first_upper = part.chars().next().is_some_and(char::is_uppercase);
        let all_upper = part
            .chars()
            .all(|c| c.is_ascii_alphabetic() && c.is_uppercase());

        if !first_upper {
            // All-lowercase: language subtag, or lowercased 4-char script tag.
            let lower = part.to_lowercase();
            if lower.len() == 4 && lower.chars().all(char::is_alphabetic) {
                // e.g. "hans" → "Hans"
                let mut cs = lower.chars();
                if let Some(first) = cs.next() {
                    script = Some(first.to_uppercase().collect::<String>() + cs.as_str());
                }
            } else {
                language = match lower.as_str() {
                    "no" => "nb".to_string(),
                    _ => lower,
                };
            }
        } else if all_upper {
            // ALL-CAPS → region subtag: TW, NO, GB, …
            region = Some(part.to_string());
        } else {
            // Starts uppercase, contains lowercase → script subtag: Hans, Cyrl, …
            script = Some(part.to_string());
        }
    }

    let mut candidates = Vec::new();
    match (&script, &region) {
        (Some(s), Some(r)) => {
            candidates.push(format!("{language}-{s}-{r}"));
            candidates.push(format!("{language}-{s}"));
        }
        (Some(s), None) => candidates.push(format!("{language}-{s}")),
        (None, Some(r)) => candidates.push(format!("{language}-{r}")),
        (None, None) => {}
    }
    candidates.push(language);
    candidates
}

/// Parse a subset of FTL: single-line `key = value` entries.
///
/// Ignores blank lines, lines starting with `#` (comments), and
/// continuation lines (those without ` = `).  Only the first occurrence
/// of a key is kept.
fn parse(ftl: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    for line in ftl.lines() {
        let trimmed = line.trim_start();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if let Some(eq) = line.find(" = ") {
            let key = line[..eq].trim().to_string();
            let value = line[eq + 3..].to_string();
            map.entry(key).or_insert(value);
        }
    }
    map
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── normalize ─────────────────────────────────────────────────────────

    #[test]
    fn normalize_simple_language() {
        assert_eq!(normalize("en"), vec!["en"]);
    }

    #[test]
    fn normalize_no_maps_to_nb() {
        assert_eq!(normalize("no"), vec!["nb"]);
    }

    #[test]
    fn normalize_language_region() {
        assert_eq!(normalize("en-GB"), vec!["en-GB", "en"]);
    }

    #[test]
    fn normalize_language_script() {
        assert_eq!(normalize("zh-Hans"), vec!["zh-Hans", "zh"]);
    }

    #[test]
    fn normalize_language_script_region() {
        assert_eq!(normalize("zh-Hans-TW"), vec!["zh-Hans-TW", "zh-Hans", "zh"]);
    }

    #[test]
    fn normalize_underscore_separator() {
        assert_eq!(normalize("zh_Hans_TW"), vec!["zh-Hans-TW", "zh-Hans", "zh"]);
    }

    #[test]
    fn normalize_private_use_tag_passthrough() {
        assert_eq!(normalize("art-x-lyaric"), vec!["art-x-lyaric"]);
    }

    #[test]
    fn normalize_all_caps_single_part_treated_as_region() {
        // ALL-CAPS is classified as region; prepended to default language "en".
        // "EN" alone has no preceding language part, so language stays "en".
        assert_eq!(normalize("EN"), vec!["en-EN", "en"]);
    }

    // ── parse ─────────────────────────────────────────────────────────────

    #[test]
    fn parse_simple_key_value() {
        let ftl = "btn-login = login\n";
        let map = parse(ftl);
        assert_eq!(map.get("btn-login").map(String::as_str), Some("login"));
    }

    #[test]
    fn parse_ignores_comments() {
        let ftl = "# This is a comment\nbtn-login = login\n";
        let map = parse(ftl);
        assert!(!map.contains_key("# This is a comment"));
        assert_eq!(map.get("btn-login").map(String::as_str), Some("login"));
    }

    #[test]
    fn parse_ignores_blank_lines() {
        let ftl = "\n\nbtn-login = login\n\n";
        let map = parse(ftl);
        assert_eq!(map.len(), 1);
    }

    #[test]
    fn parse_first_occurrence_wins() {
        let ftl = "key = first\nkey = second\n";
        let map = parse(ftl);
        assert_eq!(map.get("key").map(String::as_str), Some("first"));
    }

    #[test]
    fn parse_substitution_value_preserved() {
        let ftl = "msg = hello { $name }\n";
        let map = parse(ftl);
        assert_eq!(map.get("msg").map(String::as_str), Some("hello { $name }"));
    }

    #[test]
    fn parse_empty_string_gives_empty_map() {
        assert!(parse("").is_empty());
    }
}
