/// Embedded Scheme evaluator for the ma terminal.
///
/// # Usage
///
/// Any command line containing `(…)` is pre-processed by `expand()` before
/// normal parsing.  Each `(…)` span is evaluated as a Scheme expression and
/// the result is spliced back into the line as a string.
///
/// ## ma primitives
///
/// | Scheme form | What it does |
/// |---|---|
/// | `(.my.path)` | dot-path get (sync, returns string or child list) |
/// | `(.my.path: "val")` | dot-path set (sync, returns nil) |
/// | `(.my.path "")` | dot-path delete (sync, returns nil) |
/// | `(.my.path!verb arg…)` | side-effect verb, queued (returns nil) |
/// | `(.my.path: <bafy…>)` | set to CID content (`<cid>` fetched by eval) |
/// | `(@ma#house:enter #room)` | actor RPC (async, returns reply string) |
/// | `(did:ma:abc#room:enter ticket)` | same, DID in function position |
///
/// ## Scheme features
///
/// `define`, `lambda`, `let`, `let*`, `letrec`, `if`, `cond`, `begin`,
/// `and`, `or`, `when`, `unless`, `set!`, `quote`.
///
/// Builtins: arithmetic (`+` `-` `*` `/` `mod`), comparison (`=` `<` …),
/// list operations (`cons`, `car`, `cdr`, `map`, `filter`, `fold`, …),
/// string operations (`string-append`, `substring`, …), predicates,
/// `display`, `error`, `assert`.
///
/// ## Session environment
///
/// Definitions made with `(define …)` persist in the session environment
/// for the lifetime of the login session.  Call `reset_session_env()` on
/// logout to clear it.
pub mod eval;
pub mod parser;
pub mod value;

pub use eval::{Ctx, EvalCtx};
pub use value::{Env, SchemeVal};

use std::cell::RefCell;
use std::rc::Rc;

use leptos::prelude::RwSignal;

use crate::{config::EgoConfig, state::AppState};

// ── Session environment ────────────────────────────────────────────────────

thread_local! {
    static SESSION_ENV: RefCell<Option<Env>> = const { RefCell::new(None) };
}

/// Initialise a fresh session environment. Called at login.
pub fn init_session_env() {
    SESSION_ENV.with(|e| *e.borrow_mut() = Some(Env::new_root()));
}

/// Return the current session environment, creating one if needed.
pub(crate) fn get_env() -> Env {
    SESSION_ENV.with(|e| {
        let mut inner = e.borrow_mut();
        if inner.is_none() {
            *inner = Some(Env::new_root());
        }
        inner.as_ref().unwrap().clone()
    })
}

/// Serialise the session environment to Scheme source text.
///
/// Each top-level binding is written as a `(define …)` form.  Lambdas are
/// reconstructed from their AST.  Builtins and ma-primitives are skipped.
pub fn dump_env() -> String {
    let env = get_env();
    let pairs: Vec<(String, SchemeVal)> = {
        let mut v = env.own_bindings();
        v.sort_by(|(a, _), (b, _)| a.cmp(b));
        v
    };

    let mut lines = vec![
        "; zscheme session — generated by .my.scheme.ma!save".to_string(),
        "; Edit with .my.scheme.ma!edit  •  Reload with .my.scheme.ma!eval".to_string(),
        String::new(),
    ];
    for (name, val) in &pairs {
        if let Some(src) = val_to_define(name, val) {
            lines.push(src);
            lines.push(String::new());
        }
    }
    lines.join("\n")
}

fn val_to_define(name: &str, val: &SchemeVal) -> Option<String> {
    match val {
        SchemeVal::Str(s) => Some(format!("(define {name} {s:?})")),
        SchemeVal::Int(n) => Some(format!("(define {name} {n})")),
        SchemeVal::Float(f) => Some(format!("(define {name} {f})")),
        SchemeVal::Bool(true) => Some(format!("(define {name} #t)")),
        SchemeVal::Bool(false) => Some(format!("(define {name} #f)")),
        SchemeVal::Nil => Some(format!("(define {name} ())")),
        SchemeVal::List(items) => {
            let elems: Vec<String> = items.iter().map(val_to_src).collect();
            Some(format!("(define {name} '({}))", elems.join(" ")))
        }
        SchemeVal::Lambda {
            params, rest, body, ..
        } => {
            let param_str = match rest {
                Some(r) if params.is_empty() => format!(". {r}"),
                Some(r) => format!("{} . {r}", params.join(" ")),
                None => params.join(" "),
            };
            let body_fmt = body
                .iter()
                .map(|e| format!("\n  {}", expr_to_src(e)))
                .collect::<String>();
            Some(format!("(define ({name} {param_str}){body_fmt})"))
        }
        _ => None, // Builtins, MaPath, MaActor: no source needed
    }
}

fn val_to_src(val: &SchemeVal) -> String {
    match val {
        SchemeVal::Str(s) => format!("{s:?}"),
        SchemeVal::Int(n) => n.to_string(),
        SchemeVal::Float(f) => f.to_string(),
        SchemeVal::Bool(true) => "#t".to_string(),
        SchemeVal::Bool(false) => "#f".to_string(),
        SchemeVal::Nil => "()".to_string(),
        SchemeVal::List(items) => format!(
            "({})",
            items.iter().map(val_to_src).collect::<Vec<_>>().join(" ")
        ),
        other => other.display(),
    }
}

fn expr_to_src(expr: &parser::SchemeExpr) -> String {
    match expr {
        parser::SchemeExpr::Nil => "()".to_string(),
        parser::SchemeExpr::Str(s) => format!("{s:?}"),
        parser::SchemeExpr::Atom(s) => s.clone(),
        parser::SchemeExpr::List(fs) => {
            format!(
                "({})",
                fs.iter().map(expr_to_src).collect::<Vec<_>>().join(" ")
            )
        }
    }
}

// ── Public API ─────────────────────────────────────────────────────────────

/// Returns `true` when `line` contains at least one unescaped `(` that
/// could be a Scheme expression requiring expansion.
pub fn needs_expansion(line: &str) -> bool {
    let mut in_string = false;
    let mut escaped = false;
    for ch in line.chars() {
        if escaped {
            escaped = false;
            continue;
        }
        if ch == '\\' && in_string {
            escaped = true;
            continue;
        }
        if ch == '"' {
            in_string = !in_string;
            continue;
        }
        if in_string {
            continue;
        }
        if ch == '(' {
            return true;
        }
    }
    false
}

/// Expand all top-level `(…)` spans in `line`.
///
/// Each span is evaluated as a Scheme expression (with nested spans evaluated
/// inside-out by the Scheme evaluator) and the string result is spliced back
/// at the span's position.  The returned string is a normal ma command line
/// ready for `dispatch_eval_line`.
pub async fn expand(
    line: &str,
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<String, String> {
    let ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    let env = get_env();

    let chars: Vec<char> = line.chars().collect();
    let mut result = String::new();
    let mut pos = 0;

    while pos < chars.len() {
        if chars[pos] == '(' {
            let (end, span) = find_balanced_paren(&chars, pos)
                .ok_or_else(|| format!("unmatched '(' at column {}", pos + 1))?;
            let val = eval_span(&span, env.clone(), ctx.clone()).await?;
            result.push_str(&val.to_splice()?);
            pos = end + 1;
        } else {
            result.push(chars[pos]);
            pos += 1;
        }
    }

    Ok(result)
}

/// Evaluate all top-level Scheme forms in `content` (typically `define`
/// statements), then call `(verb arg…)` in the same session environment.
///
/// Runs sequentially in a single async task — no race condition with the
/// dispatch queue.  Arguments are passed as Scheme string literals.
pub async fn call_content(
    content: &str,
    verb: &str,
    args: &[String],
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<SchemeVal, String> {
    let env = get_env();
    let ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    // Evaluate each top-level form in the content (defines, lambdas, …)
    let tokens = parser::tokenize(content).map_err(|e| e.to_string())?;
    let mut pos = 0;
    while pos < tokens.len() {
        let (expr, next) = parser::parse_expr(&tokens, pos).map_err(|e| e.to_string())?;
        eval::eval(expr, env.clone(), ctx.clone())
            .await
            .map_err(|e| e.to_string())?;
        pos = next;
    }
    // Build and evaluate (verb "arg1" "arg2" …)
    eval_span(&build_call_str(verb, args), env, ctx).await
}

/// Build a Scheme function-call string: `(verb "arg1" "arg2" …)`.
/// Arguments are shell-split tokens from the command line; each is
/// passed as a Scheme string literal (double-quoted).
fn build_call_str(verb: &str, args: &[String]) -> String {
    if args.is_empty() {
        format!("({verb})")
    } else {
        let quoted: Vec<String> = args.iter().map(|a| format!("{a:?}")).collect();
        format!("({verb} {})", quoted.join(" "))
    }
}

// ── Internal helpers ───────────────────────────────────────────────────────

/// Find the closing paren matching the `(` at `chars[start]`.
///
/// Correctly handles:
/// - nested parentheses
/// - string literals (parens inside strings are ignored)
/// - `\"` escape sequences inside strings
///
/// Returns `(end_index, full_span_string)` on success.
fn find_balanced_paren(chars: &[char], start: usize) -> Option<(usize, String)> {
    debug_assert_eq!(chars[start], '(');
    let mut depth: usize = 0;
    let mut in_string = false;
    let mut escaped = false;

    for (i, &ch) in chars.iter().enumerate().skip(start) {
        if escaped {
            escaped = false;
            continue;
        }
        if ch == '\\' && in_string {
            escaped = true;
            continue;
        }
        if ch == '"' {
            in_string = !in_string;
            continue;
        }
        if in_string {
            continue;
        }
        if ch == '(' {
            depth += 1;
        } else if ch == ')' {
            depth -= 1;
            if depth == 0 {
                let s: String = chars[start..=i].iter().collect();
                return Some((i, s));
            }
        }
    }
    None
}

/// Parse and evaluate one `(…)` span string.
async fn eval_span(span: &str, env: Env, ctx: Ctx) -> Result<SchemeVal, String> {
    use parser::{parse_expr, tokenize};
    let tokens = tokenize(span).map_err(|e| e.to_string())?;
    let (expr, _) = parse_expr(&tokens, 0).map_err(|e| e.to_string())?;
    eval::eval(expr, env, ctx).await.map_err(|e| e.to_string())
}
