/// Embedded Scheme evaluator for the ma terminal — wired to ma-zscheme.
pub mod eval;
pub mod parser;
pub mod value;

pub use eval::{Ctx, EvalCtx};
pub use ma_zscheme::{Env, SchemeVal};

use crate::{config::EgoConfig, state::AppState};
use leptos::prelude::RwSignal;
use std::rc::Rc;

// ── Session environment (delegated to ma-zscheme) ──────────────────────────

pub fn init_session_env() {
    ma_zscheme::init_session_env();
}
pub(crate) fn get_env() -> Env {
    ma_zscheme::get_env()
}

// ── Session-env serialisation ──────────────────────────────────────────────

pub fn dump_env() -> String {
    let env = get_env();
    let mut pairs: Vec<(String, SchemeVal)> = env.own_bindings();
    pairs.sort_by(|(a, _), (b, _)| a.cmp(b));

    let mut lines = vec![
        "; zscheme session — generated by /my/scheme/ma!save".to_string(),
        "; Edit with /my/scheme/ma!edit  •  Reload with /my/scheme/ma!eval".to_string(),
        String::new(),
    ];
    for (name, val) in &pairs {
        if let Some(src) = val_to_define(name, val) {
            lines.push(src);
            lines.push(String::new());
        }
    }
    lines.join("\n")
}

fn val_to_define(name: &str, val: &SchemeVal) -> Option<String> {
    match val {
        SchemeVal::Str(s) => Some(format!("(define {name} {s:?})")),
        SchemeVal::Int(n) => Some(format!("(define {name} {n})")),
        SchemeVal::Float(f) => Some(format!("(define {name} {f})")),
        SchemeVal::Bool(true) => Some(format!("(define {name} #t)")),
        SchemeVal::Bool(false) => Some(format!("(define {name} #f)")),
        SchemeVal::Nil => Some(format!("(define {name} ())")),
        SchemeVal::List(items) => {
            let elems: Vec<String> = items.iter().map(val_to_src).collect();
            Some(format!("(define {name} '({}))", elems.join(" ")))
        }
        SchemeVal::Lambda {
            params, rest, body, ..
        } => {
            let param_str = match rest {
                Some(r) if params.is_empty() => format!(". {r}"),
                Some(r) => format!("{} . {r}", params.join(" ")),
                None => params.join(" "),
            };
            let body_fmt = body
                .iter()
                .map(|e| format!("\n  {}", expr_to_src(e)))
                .collect::<String>();
            Some(format!("(define ({name} {param_str}){body_fmt})"))
        }
        _ => None,
    }
}

fn val_to_src(val: &SchemeVal) -> String {
    match val {
        SchemeVal::Str(s) => format!("{s:?}"),
        SchemeVal::Int(n) => n.to_string(),
        SchemeVal::Float(f) => f.to_string(),
        SchemeVal::Bool(true) => "#t".to_string(),
        SchemeVal::Bool(false) => "#f".to_string(),
        SchemeVal::Nil => "()".to_string(),
        SchemeVal::List(items) => format!(
            "({})",
            items.iter().map(val_to_src).collect::<Vec<_>>().join(" ")
        ),
        other => other.display(),
    }
}

fn expr_to_src(expr: &parser::SchemeExpr) -> String {
    match expr {
        parser::SchemeExpr::Nil => "()".to_string(),
        parser::SchemeExpr::Str(s) => format!("{s:?}"),
        parser::SchemeExpr::Atom(s) => s.clone(),
        parser::SchemeExpr::List(fs) => format!(
            "({})",
            fs.iter().map(expr_to_src).collect::<Vec<_>>().join(" ")
        ),
    }
}

// ── Command-line expansion ─────────────────────────────────────────────────

pub fn needs_expansion(line: &str) -> bool {
    let mut in_string = false;
    let mut escaped = false;
    for ch in line.chars() {
        if escaped {
            escaped = false;
            continue;
        }
        if ch == '\\' && in_string {
            escaped = true;
            continue;
        }
        if ch == '"' {
            in_string = !in_string;
            continue;
        }
        if in_string {
            continue;
        }
        if ch == '(' {
            return true;
        }
    }
    false
}

pub async fn expand(
    line: &str,
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<String, String> {
    let ctx: Ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    let env = get_env();
    let chars: Vec<char> = line.chars().collect();
    let mut result = String::new();
    let mut pos = 0;
    while pos < chars.len() {
        if chars[pos] == '(' {
            let (end, span) = find_balanced_paren(&chars, pos)
                .ok_or_else(|| format!("unmatched '(' at column {}", pos + 1))?;
            let val = eval_span(&span, env.clone(), ctx.clone()).await?;
            result.push_str(&val.to_splice()?);
            pos = end + 1;
        } else {
            result.push(chars[pos]);
            pos += 1;
        }
    }
    Ok(result)
}

pub async fn call_content(
    content: &str,
    verb: &str,
    args: &[String],
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<SchemeVal, String> {
    let env = get_env();
    let ctx: Ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    let tokens = parser::tokenize(content).map_err(|e| e.to_string())?;
    let mut pos = 0;
    while pos < tokens.len() {
        let (expr, next) = parser::parse_expr(&tokens, pos).map_err(|e| e.to_string())?;
        ma_zscheme::eval::eval(expr, env.clone(), ctx.clone())
            .await
            .map_err(|e| e.to_string())?;
        pos = next;
    }
    eval_span(&build_call_str(verb, args), env, ctx).await
}

fn build_call_str(verb: &str, args: &[String]) -> String {
    if args.is_empty() {
        format!("({verb})")
    } else {
        let q: Vec<String> = args.iter().map(|a| format!("{a:?}")).collect();
        format!("({verb} {})", q.join(" "))
    }
}

fn find_balanced_paren(chars: &[char], start: usize) -> Option<(usize, String)> {
    debug_assert_eq!(chars[start], '(');
    let mut depth: usize = 0;
    let mut in_string = false;
    let mut escaped = false;
    for (i, &ch) in chars.iter().enumerate().skip(start) {
        if escaped {
            escaped = false;
            continue;
        }
        if ch == '\\' && in_string {
            escaped = true;
            continue;
        }
        if ch == '"' {
            in_string = !in_string;
            continue;
        }
        if in_string {
            continue;
        }
        if ch == '(' {
            depth += 1;
        } else if ch == ')' {
            depth -= 1;
            if depth == 0 {
                return Some((i, chars[start..=i].iter().collect()));
            }
        }
    }
    None
}

async fn eval_span(span: &str, env: Env, ctx: Ctx) -> Result<SchemeVal, String> {
    let tokens = parser::tokenize(span).map_err(|e| e.to_string())?;
    let (expr, _) = parser::parse_expr(&tokens, 0).map_err(|e| e.to_string())?;
    ma_zscheme::eval::eval(expr, env, ctx)
        .await
        .map_err(|e| e.to_string())
}
