/// Embedded Scheme evaluator for the ma terminal — wired to ma-zscheme.
pub mod eval;
pub mod parser;
pub mod value;

pub use eval::{Ctx, EvalCtx};
pub use ma_zscheme::{Env, SchemeVal};

use crate::{config::EgoConfig, state::AppState};
use leptos::prelude::RwSignal;
use std::rc::Rc;

// ── Session environment (delegated to ma-zscheme) ──────────────────────────

pub fn init_session_env() {
    ma_zscheme::init_session_env();
}
pub fn reset_session_env() {
    ma_zscheme::reset_session_env();
}
pub(crate) fn get_env() -> Env {
    ma_zscheme::get_env()
}

pub(crate) fn has_event_handler() -> bool {
    matches!(get_env().get("on-event"), Some(SchemeVal::Lambda { .. }))
}

/// Invoke the local event entry point with decoded, typed event data.
///
/// Event values are placed in a child environment and referenced by a fixed
/// AST. They are never serialised into or parsed from Scheme source.
pub async fn call_event(
    event: &str,
    args: Vec<SchemeVal>,
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<SchemeVal, String> {
    let env = Env::extend(&get_env());
    env.define("__ma_event_args", SchemeVal::List(args));
    let expr = parser::SchemeExpr::List(vec![
        parser::SchemeExpr::Atom("on-event".to_string()),
        parser::SchemeExpr::Str(event.to_string()),
        parser::SchemeExpr::Atom("__ma_event_args".to_string()),
    ]);
    let ctx: Ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    ma_zscheme::eval::eval(expr, env, ctx)
        .await
        .map_err(|error| error.to_string())
}

// ── Session-env serialisation ──────────────────────────────────────────────

pub fn dump_env() -> String {
    let env = get_env();
    let mut pairs: Vec<(String, SchemeVal)> = env.own_bindings();
    pairs.sort_by(|(a, _), (b, _)| a.cmp(b));

    let mut lines = vec![
        "; zscheme session — generated by .my.scheme.ma!save".to_string(),
        "; Edit with .my.scheme.ma!edit  •  Reload with .my.scheme.ma!eval".to_string(),
        String::new(),
    ];
    for (name, val) in &pairs {
        if let Some(src) = val_to_define(name, val) {
            lines.push(src);
            lines.push(String::new());
        }
    }
    lines.join("\n")
}

fn val_to_define(name: &str, val: &SchemeVal) -> Option<String> {
    match val {
        SchemeVal::Str(s) => Some(format!("(define {name} {s:?})")),
        SchemeVal::Int(n) => Some(format!("(define {name} {n})")),
        SchemeVal::Float(f) => Some(format!("(define {name} {f})")),
        SchemeVal::Bool(true) => Some(format!("(define {name} #t)")),
        SchemeVal::Bool(false) => Some(format!("(define {name} #f)")),
        SchemeVal::Nil => Some(format!("(define {name} ())")),
        SchemeVal::List(items) => {
            let elems: Vec<String> = items.iter().map(val_to_src).collect();
            Some(format!("(define {name} '({}))", elems.join(" ")))
        }
        SchemeVal::Map(_) => Some(format!("(define {name} {})", val_to_src(val))),
        SchemeVal::Lambda {
            params, rest, body, ..
        } => {
            let param_str = match rest {
                Some(r) if params.is_empty() => format!(". {r}"),
                Some(r) => format!("{} . {r}", params.join(" ")),
                None => params.join(" "),
            };
            let body_fmt = body
                .iter()
                .map(|e| format!("\n  {}", expr_to_src(e)))
                .collect::<String>();
            Some(format!("(define ({name} {param_str}){body_fmt})"))
        }
        _ => None,
    }
}

fn val_to_src(val: &SchemeVal) -> String {
    match val {
        SchemeVal::Str(s) => format!("{s:?}"),
        SchemeVal::Int(n) => n.to_string(),
        SchemeVal::Float(f) => f.to_string(),
        SchemeVal::Bool(true) => "#t".to_string(),
        SchemeVal::Bool(false) => "#f".to_string(),
        SchemeVal::Nil => "()".to_string(),
        SchemeVal::List(items) => format!(
            "({})",
            items.iter().map(val_to_src).collect::<Vec<_>>().join(" ")
        ),
        SchemeVal::Map(map) => {
            let elems = map
                .iter()
                .map(|(key, value)| format!("{key:?} {}", val_to_src(value)))
                .collect::<Vec<_>>()
                .join(" ");
            format!("(make-map {elems})")
        }
        other => other.display(),
    }
}

fn expr_to_src(expr: &parser::SchemeExpr) -> String {
    match expr {
        parser::SchemeExpr::Nil => "()".to_string(),
        parser::SchemeExpr::Str(s) => format!("{s:?}"),
        parser::SchemeExpr::Atom(s) => s.clone(),
        parser::SchemeExpr::List(fs) => format!(
            "({})",
            fs.iter().map(expr_to_src).collect::<Vec<_>>().join(" ")
        ),
    }
}

// ── Command-line expansion ─────────────────────────────────────────────────

pub fn needs_expansion(line: &str) -> bool {
    let line = parser::strip_comments(line);
    let mut quote: Option<char> = None;
    let mut escaped = false;
    for ch in line.chars() {
        if escaped {
            escaped = false;
            continue;
        }
        if ch == '\\' && quote.is_some() {
            escaped = true;
            continue;
        }
        if let Some(q) = quote {
            if ch == q {
                quote = None;
            }
            continue;
        }
        if ch == '"' || ch == '\'' {
            quote = Some(ch);
            continue;
        }
        if ch == '(' {
            return true;
        }
    }
    false
}

pub(crate) fn has_incomplete_expression(line: &str) -> bool {
    let line = parser::strip_comments(line);
    let chars: Vec<char> = line.chars().collect();
    let mut pos = 0;
    let mut quote: Option<char> = None;
    let mut escaped = false;
    while pos < chars.len() {
        let ch = chars[pos];
        if escaped {
            escaped = false;
            pos += 1;
            continue;
        }
        if ch == '\\' && quote.is_some() {
            escaped = true;
            pos += 1;
            continue;
        }
        if let Some(q) = quote {
            if ch == q {
                quote = None;
            }
            pos += 1;
            continue;
        }
        if ch == '"' || ch == '\'' {
            quote = Some(ch);
            pos += 1;
            continue;
        }
        if ch == '(' {
            let Some((end, _)) = find_balanced_paren(&chars, pos) else {
                return true;
            };
            pos = end + 1;
            continue;
        }
        pos += 1;
    }
    false
}

pub async fn expand(
    line: &str,
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<String, String> {
    let ctx: Ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    let env = get_env();
    let line = parser::strip_comments(line);
    let chars: Vec<char> = line.chars().collect();
    let mut result = String::new();
    let mut pos = 0;
    let mut quote: Option<char> = None;
    let mut escaped = false;
    while pos < chars.len() {
        let ch = chars[pos];
        if escaped {
            result.push(ch);
            escaped = false;
            pos += 1;
            continue;
        }
        if ch == '\\' && quote.is_some() {
            result.push(ch);
            escaped = true;
            pos += 1;
            continue;
        }
        if let Some(q) = quote {
            result.push(ch);
            if ch == q {
                quote = None;
            }
            pos += 1;
            continue;
        }
        if ch == '"' || ch == '\'' {
            quote = Some(ch);
            result.push(ch);
            pos += 1;
            continue;
        }
        if ch == '(' {
            let (end, span) = find_balanced_paren(&chars, pos)
                .ok_or_else(|| format!("unmatched '(' at column {}", pos + 1))?;
            let val = eval_span(&span, env.clone(), ctx.clone()).await?;
            result.push_str(&val.to_splice()?);
            pos = end + 1;
        } else {
            result.push(ch);
            pos += 1;
        }
    }
    Ok(result)
}

/// Evaluate one complete Scheme expression entered as a terminal line.
///
/// Returns `Ok(None)` when the line contains text beyond the expression, so
/// callers can use normal command-line expansion instead.
pub async fn eval_standalone(
    line: &str,
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<Option<SchemeVal>, String> {
    let tokens = parser::tokenize(line).map_err(|error| error.to_string())?;
    let (expr, next) = parser::parse_expr(&tokens, 0).map_err(|error| error.to_string())?;
    if next != tokens.len() {
        return Ok(None);
    }
    let ctx: Ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    ma_zscheme::eval::eval(expr, get_env(), ctx)
        .await
        .map(Some)
        .map_err(|error| error.to_string())
}

pub async fn call_content(
    content: &str,
    verb: &str,
    args: &[String],
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<SchemeVal, String> {
    let env = get_env();
    let ctx: Ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    load_content_into_env(content, env.clone(), ctx.clone()).await?;
    eval_span(&build_call_str(verb, args), env, ctx).await
}

/// Evaluate local Scheme source into the current session environment.
///
/// Callers supply only trusted local profile content. This function never
/// resolves a DID, CID, or other remote source on its own.
#[cfg(test)]
pub async fn load_content(
    content: &str,
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<(), String> {
    let env = get_env();
    let ctx: Ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    load_content_into_env(content, env, ctx).await
}

/// Build a fresh session from the stable Scheme layer and then the avatar.
/// The candidate is installed only after both layers evaluate successfully.
pub async fn bootstrap_session(
    scheme_source: &str,
    avatar_source: &str,
    state: &AppState,
    config: RwSignal<EgoConfig>,
) -> Result<(), String> {
    let env = Env::new_root();
    let ctx: Ctx = Rc::new(EvalCtx {
        state: state.clone(),
        config,
    });
    load_content_into_env(scheme_source, env.clone(), ctx.clone()).await?;
    load_content_into_env(avatar_source, env.clone(), ctx).await?;
    ma_zscheme::install_session_env(env);
    Ok(())
}

async fn load_content_into_env(content: &str, env: Env, ctx: Ctx) -> Result<(), String> {
    let tokens = parser::tokenize(content).map_err(|e| e.to_string())?;
    let mut pos = 0;
    while pos < tokens.len() {
        let (expr, next) = parser::parse_expr(&tokens, pos).map_err(|e| e.to_string())?;
        ma_zscheme::eval::eval(expr, env.clone(), ctx.clone())
            .await
            .map_err(|e| e.to_string())?;
        pos = next;
    }
    Ok(())
}

fn build_call_str(verb: &str, args: &[String]) -> String {
    if args.is_empty() {
        format!("({verb})")
    } else {
        let q: Vec<String> = args.iter().map(|a| format!("{a:?}")).collect();
        format!("({verb} {})", q.join(" "))
    }
}

fn find_balanced_paren(chars: &[char], start: usize) -> Option<(usize, String)> {
    debug_assert_eq!(chars[start], '(');
    let mut depth: usize = 0;
    let mut in_string = false;
    let mut escaped = false;
    for (i, &ch) in chars.iter().enumerate().skip(start) {
        if escaped {
            escaped = false;
            continue;
        }
        if ch == '\\' && in_string {
            escaped = true;
            continue;
        }
        if in_string {
            if ch == '"' {
                in_string = false;
            }
            continue;
        }
        if ch == '"' {
            in_string = true;
            continue;
        }
        if ch == '(' {
            depth += 1;
        } else if ch == ')' {
            depth -= 1;
            if depth == 0 {
                return Some((i, chars[start..=i].iter().collect()));
            }
        }
    }
    None
}

async fn eval_span(span: &str, env: Env, ctx: Ctx) -> Result<SchemeVal, String> {
    let tokens = parser::tokenize(span).map_err(|e| e.to_string())?;
    let (expr, _) = parser::parse_expr(&tokens, 0).map_err(|e| e.to_string())?;
    ma_zscheme::eval::eval(expr, env, ctx)
        .await
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{config::EgoConfig, core::Entry, state::AppState};
    use futures::executor::block_on;
    use leptos::prelude::{Owner, RwSignal, WithUntracked};

    #[test]
    fn needs_expansion_ignores_single_quoted_parentheses() {
        assert!(!needs_expansion(
            "make thing '(begin (set-prop! \"name\" \"Lamp\"))'"
        ));
    }

    #[test]
    fn needs_expansion_ignores_double_quoted_parentheses() {
        assert!(!needs_expansion("say \"not (scheme)\""));
    }

    #[test]
    fn needs_expansion_detects_unquoted_parentheses() {
        assert!(needs_expansion(
            "make thing (string-append (#.my.things.lamp))"
        ));
    }

    #[test]
    fn find_balanced_paren_ignores_quoted_parentheses() {
        let chars: Vec<char> = "(display \"(not the end)\") tail".chars().collect();
        let (end, span) = find_balanced_paren(&chars, 0).expect("balanced expression");
        assert_eq!(span, "(display \"(not the end)\")");
        assert_eq!(end, span.len() - 1);
    }

    #[test]
    fn find_balanced_paren_treats_apostrophe_as_scheme_quote_prefix() {
        let chars: Vec<char> = "(begin '(define foo \"bar\")) tail".chars().collect();
        let (end, span) = find_balanced_paren(&chars, 0).expect("balanced expression");
        assert_eq!(span, "(begin '(define foo \"bar\"))");
        assert_eq!(end, span.len() - 1);
    }

    #[test]
    fn find_balanced_paren_does_not_require_closing_apostrophe() {
        let chars: Vec<char> = "(foo' shdkjhj) tail".chars().collect();
        let (end, span) = find_balanced_paren(&chars, 0).expect("balanced expression");
        assert_eq!(span, "(foo' shdkjhj)");
        assert_eq!(end, span.len() - 1);
    }

    #[test]
    fn incomplete_expression_ignores_quoted_parentheses() {
        assert!(!has_incomplete_expression(
            "say \"an (unclosed parenthesis\""
        ));
        assert!(has_incomplete_expression("say (string-append \"open\""));
    }

    #[test]
    fn load_content_defines_local_session_functions() {
        let _owner = Owner::new();
        let state = AppState::new();
        let config = RwSignal::new(EgoConfig::new());
        init_session_env();

        block_on(load_content(
            "(define (avatar-bootstrap) \"ready\")",
            &state,
            config,
        ))
        .expect("local source loads");

        let value = block_on(call_content("", "avatar-bootstrap", &[], &state, config))
            .expect("loaded local function is callable");
        assert!(matches!(value, SchemeVal::Str(ref text) if text == "ready"));
    }

    #[test]
    fn bootstrap_loads_scheme_before_avatar() {
        let _owner = Owner::new();
        let state = AppState::new();
        let config = RwSignal::new(EgoConfig::new());
        init_session_env();

        block_on(bootstrap_session(
            "(define dialect-value 40)",
            "(define avatar-value (+ dialect-value 2))",
            &state,
            config,
        ))
        .expect("bootstrap succeeds");

        assert!(matches!(
            get_env().get("avatar-value"),
            Some(SchemeVal::Int(42))
        ));
    }

    #[test]
    fn failed_bootstrap_does_not_install_partial_candidate() {
        let _owner = Owner::new();
        let state = AppState::new();
        let config = RwSignal::new(EgoConfig::new());
        init_session_env();
        block_on(load_content("(define existing-value 1)", &state, config))
            .expect("existing session loads");

        let error = block_on(bootstrap_session(
            "(define partial-value 2) (error \"broken dialect\")",
            "(define avatar-value 3)",
            &state,
            config,
        ))
        .expect_err("bootstrap fails");

        assert!(error.contains("broken dialect"));
        assert!(matches!(
            get_env().get("existing-value"),
            Some(SchemeVal::Int(1))
        ));
        assert!(get_env().get("partial-value").is_none());
        assert!(get_env().get("avatar-value").is_none());
    }

    #[test]
    fn standalone_expression_returns_its_value() {
        let _owner = Owner::new();
        let state = AppState::new();
        let config = RwSignal::new(EgoConfig::new());
        init_session_env();

        let value = block_on(eval_standalone("(+ 20 22)", &state, config))
            .expect("expression evaluates")
            .expect("line is a standalone expression");
        assert!(matches!(value, SchemeVal::Int(42)));

        assert!(block_on(eval_standalone("say (+ 20 22)", &state, config))
            .expect("non-standalone input parses")
            .is_none());
    }

    #[test]
    fn call_event_passes_network_text_as_a_typed_value() {
        let _owner = Owner::new();
        let state = AppState::new();
        let config = RwSignal::new(EgoConfig::new());
        init_session_env();

        block_on(load_content(
            "(define (on-event event args) (car args))",
            &state,
            config,
        ))
        .expect("local source loads");

        let value = block_on(call_event(
            ":print",
            vec![SchemeVal::Str("(error \"must not run\")".to_string())],
            &state,
            config,
        ))
        .expect("event handler is callable");
        assert!(matches!(value, SchemeVal::Str(ref text) if text == "(error \"must not run\")"));
    }

    #[test]
    fn default_avatar_displays_typed_speech_events() {
        let _owner = Owner::new();
        let state = AppState::new();
        let config = RwSignal::new(EgoConfig::new());
        init_session_env();
        block_on(load_content(
            crate::config::DEFAULT_AVATAR_SOURCE,
            &state,
            config,
        ))
        .expect("default avatar source loads");
        let mut ctx = std::collections::BTreeMap::new();
        ctx.insert("did".to_string(), SchemeVal::Str("did:ma:duck".to_string()));
        ctx.insert("nick".to_string(), SchemeVal::Str("Duckie".to_string()));

        block_on(call_event(
            ":say",
            vec![SchemeVal::Map(ctx), SchemeVal::Str("Kvakk!".to_string())],
            &state,
            config,
        ))
        .expect("speech event is handled");

        let text = state.entries.with_untracked(|entries| {
            entries.iter().find_map(|entry| match entry {
                Entry::System(record) => Some(record.text.clone()),
                _ => None,
            })
        });
        assert_eq!(text.as_deref(), Some("Duckie: Kvakk!"));
    }

    #[test]
    fn default_avatar_handles_every_standard_event() {
        let _owner = Owner::new();
        let state = AppState::new();
        let config = RwSignal::new(EgoConfig::new());
        init_session_env();
        block_on(load_content(
            crate::config::DEFAULT_AVATAR_SOURCE,
            &state,
            config,
        ))
        .expect("default avatar source loads");
        let mut ctx = std::collections::BTreeMap::new();
        ctx.insert("did".to_string(), SchemeVal::Str("did:ma:duck".to_string()));
        ctx.insert("nick".to_string(), SchemeVal::Str("Duckie".to_string()));
        let subject = SchemeVal::Map(ctx);
        let events = vec![
            (":print", vec![SchemeVal::Str("Kvakk!".to_string())]),
            (":arrive", vec![subject.clone()]),
            (":leave", vec![subject.clone()]),
            (
                ":say",
                vec![subject.clone(), SchemeVal::Str("Kvakk!".to_string())],
            ),
            (
                ":emote",
                vec![subject.clone(), SchemeVal::Str("waddles".to_string())],
            ),
            (":take", vec![subject.clone()]),
            (":drop", vec![subject.clone()]),
            (
                ":dig",
                vec![subject.clone(), SchemeVal::Str("north".to_string())],
            ),
            (":fill", vec![subject, SchemeVal::Str("north".to_string())]),
        ];

        for (event, args) in events {
            block_on(call_event(event, args, &state, config)).expect("standard event is handled");
        }

        let displays = state.entries.with_untracked(|entries| {
            entries
                .iter()
                .filter(|entry| matches!(entry, Entry::System(_)))
                .count()
        });
        assert_eq!(displays, 9);
    }

    #[test]
    fn default_avatar_exposes_only_the_event_handler() {
        let _owner = Owner::new();
        let state = AppState::new();
        let config = RwSignal::new(EgoConfig::new());
        init_session_env();

        block_on(load_content(
            crate::config::DEFAULT_AVATAR_SOURCE,
            &state,
            config,
        ))
        .expect("default avatar source loads");

        assert!(has_event_handler());
        assert!(get_env().get("look").is_none());
        assert!(get_env().get("go").is_none());
    }
}
